version: '3.8'

services:
  app:
    build: .
    container_name: mysite_app
    restart: always
    environment:
      - DB_HOST=db
      - DB_NAME=tsj_db
      - DB_USER=tsj_user
      - DB_PASS=secret_password
      # выкл. капчу и почту для локальной разработки
      - DISABLE_TURNSTILE=1
      - DISABLE_EMAIL=1
    volumes:
      # монтируем только публичную часть, остальной код берётся из образа
      - ./public:/var/www/mysite
      # сохраняем vendor из образа в отдельном Docker-томе
      - vendor_data:/var/www/mysite/vendor
      # (если захотите править зависимости локально, вместо тома
      # раскомментируйте строку ниже и запустите `composer install`
      # на хосте)
      # - ./vendor:/var/www/mysite/vendor:ro
      - ./private:/var/www/private:rw
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: mysite_nginx
    restart: always
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./public:/var/www/mysite:ro  # только public!
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: tsj_postgres
    restart: always
    environment:
      POSTGRES_DB: tsj_db
      POSTGRES_USER: tsj_user
      POSTGRES_PASSWORD: secret_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  db_data:
  vendor_data: